name: askpdf

services:
  db:
    image: postgres:latest
    container_name: dev_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: askpdf
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: dev_adminer
    restart: always
    ports:
      - "8080:8080"
