"""set conversation_id to nullable in Document

Revision ID: 276449438b1a
Revises: 8cbc66ec8f1c
Create Date: 2025-09-03 11:59:47.383964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276449438b1a'
down_revision: Union[str, Sequence[str], None] = '8cbc66ec8f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
