"""change Document FK type

Revision ID: 3bb2784c6d9c
Revises: 87dfaca2da83
Create Date: 2025-11-14 17:36:12.643157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb2784c6d9c'
down_revision: Union[str, Sequence[str], None] = '87dfaca2da83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conversations', ['id'])
    op.create_unique_constraint(None, 'documents', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'revoked_ref_tokens', ['id'])
    op.create_unique_constraint(None, 'temp_documents', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'temp_documents', type_='unique')
    op.drop_constraint(None, 'revoked_ref_tokens', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_constraint(None, 'conversations', type_='unique')
    # ### end Alembic commands ###
