"""update TempDocument and Document

Revision ID: 62ed9ae73b28
Revises: 95e2b5b3245b
Create Date: 2025-09-02 18:38:58.244893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ed9ae73b28'
down_revision: Union[str, Sequence[str], None] = '95e2b5b3245b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'conversations', ['id'])
    op.create_unique_constraint(None, 'documents', ['id'])
    op.create_unique_constraint(None, 'temp_documents', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temp_documents', type_='unique')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_constraint(None, 'conversations', type_='unique')
    # ### end Alembic commands ###
