AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  A simple Lambda function.

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 90
      MemorySize: 1024
      Architectures:
        - x86_64 # or arm64
      Environment:
        Variables:
          VDB_URI: ""
          VDB_PORT: 8000
          VDB_SECRET_KEY: ""
          HOOK_URL: "test"
          HOOK_SECRET: "test"

    Metadata:
      DockerTag: process_file_v0
      DockerContext: ./functions/process_file # Directory containing Dockerfile
      Dockerfile: Dockerfile # Name of your Dockerfile
