name: Deploy AWS Lambda

on:
  push:
    branches:
      - master
    paths:
      - "server/lambda/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required to check out the repository
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::615299737342:role/GitHubAction-LambdaDeployRole
          aws-region: ap-south-1

      - name: Install Python dependencies
        run: |
          pip install \
            -r ./server/lambda/functions/process_file/requirements.txt \
            -t ./server/lambda/functions/process_file/

      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: docsToVectors
          code-artifacts-dir: ./server/lambda/functions/process_file/
